### ISSUE TITLE
IP Block error

### ISSUE THREAD

**Issue by heshamgamal410** [aandrew-me/tgpt#2]
![Screenshot from 2023-04-22 19-02-17](https://user-images.githubusercontent.com/91227805/233797332-0e340df9-5b30-4878-948f-0a850b6194eb.png)
It doesn't mention what is the error.
BTW I'm using Fedora Linux 38

**Comment by aandrew-me** [comment]
Hello,
that's really strange. It could be something related to network. Are you able to access this site https://chatbot.theb.ai/?

**Comment by aandrew-me** [comment]
Also try again with other questions

**Comment by heshamgamal410** [comment]
It's not a network issue, I can access the website and interact with it.
And also tried asking different questions on different OSs (Fedora Linux and windows 11)  and still the same issue.

**Comment by neer3** [comment]
The same is happening in my case, I am also able to access the site.

**Comment by ezynda3** [comment]
Same...

**Comment by aandrew-me** [comment]
> It's not a network issue, I can access the website and interact with it. And also tried asking different questions on different OSs (Fedora Linux and windows 11) and still the same issue.

I am making an update and it will make the error messages more detailed. This error message happens when the application is unable to parse the data returned.

**Comment by aandrew-me** [comment]
Can you try if this problem persists with a proxy or vpn?

**Comment by aandrew-me** [comment]
Looks like this problem is related to your IP address. The server is blocking it

**Comment by heshamgamal410** [comment]
Still the same output with Proton vpn 
(Error. Your IP is being blocked by the server.
Status Code: 403)

**Comment by aandrew-me** [comment]
> Still the same output with Proton vpn (Error. Your IP is being blocked by the server. Status Code: 403)

Yes with ProtonVPN I also get that error. Try windscribe

**Comment by aandrew-me** [comment]
So its understandable that this is not the problem of the program, rather for some reason the server is not responding to your IP.

**Comment by heshamgamal410** [comment]
I don't have windscribe to test it unfortunately.

**Comment by heshamgamal410** [comment]
But if someone else is facing the same problem, i'll leave the issue open till there is a workaround for it.

**Comment by aandrew-me** [comment]
> But if someone else is facing the same problem, i'll leave the issue open till there is a workaround for it.

I am afraid there is nothing to do from my side. However try with Windscribe. They have a program for Windows, Macos and Linux and its free.

**Comment by heshamgamal410** [comment]
Thanks for the effort but it didn't work with windscribe as well, it's not a big deal I'll keep using it in the browser

**Comment by hunsrus** [comment]
I'm using Arch and having the same problem, it returns:
```
Error. Your IP is being blocked by the server.
Status Code: 403
```

**Comment by akhan4u** [comment]
Using Ubuntu 22.04 and not behind any VPN. Getting same error

```bash
Error. Your IP is being blocked by the server.
Status Code: 403
```

**Comment by aandrew-me** [comment]
Guys I will be pushing a new update soon. Let me know if it solves the problem

**Comment by aandrew-me** [comment]
Guys on Linux, can you see when you run this command if you get `HTTP/2 403` or `HTTP/2 200` at the top

```
curl -i -s -k -X $'POST' \
    -H $'Host: chatbot.theb.ai' -H $'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0' -H $'Accept: application/json, text/plain, */*' -H $'Accept-Language: en-US,en;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Content-Type: application/json' -H $'Content-Length: 89' -H $'Origin: https://chatbot.theb.ai' -H $'Referer: https://chatbot.theb.ai/' -H $'Sec-Fetch-Dest: empty' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Site: same-origin' -H $'Te: trailers' \
    -b $'__cf_bm=abcdefghij=' \
    --data-binary $'{\"prompt\":\"Hello\",\"options\":{\"parentMessageId\":\"chatcmpl-78PgZsGQgryrTShwudK0aQXhsEBSH\"}}' \
    $'https://chatbot.theb.ai/api/chat-process'
```

**Comment by vpn12** [comment]
Getting HTTP/2 200 after running the curl command.
But still getting error.
~ ❯ tgpt "Explain quantum computing in simple terms"
Explain quantum computing in simple terms

Error. Your IP is being blocked by the server.
Status Code: 403

Installed tgpt 1.2.0 from aur

**Comment by aandrew-me** [comment]
> Getting HTTP/2 200 after running the curl command. But still getting error. ~ ❯ tgpt "Explain quantum computing in simple terms" Explain quantum computing in simple terms
> 
> Error. Your IP is being blocked by the server. Status Code: 403
> 
> Installed tgpt 1.2.0 from aur

Thanks for reporting. I am having a hard time figuring out why its happening

**Comment by xplshn** [comment]
Same here :(

**Comment by btwitsmyname** [comment]
I tried running this in some of the ways mentioned above, the first output was correct (I asked it about Minecraft) the second output was "%!s(<nil>)" until i asked it "what is 1+1", first I got "status code: 400(Bad Request)" after I tried using it with a vpn (proton) and got "status Code: 403(Forbidden response)", and I am able to access BAI from my browser.

**Comment by btwitsmyname** [comment]
I don't know anything about go but I asked chat gpt to add an ip rotater and that fixed the issue for me.

**Comment by btwitsmyname** [comment]
IP-rotater
just to explain i had chat GPT add this but from my understanding
their is an added structure of ip's that changes pre-entered ip's before and after each use


CODE:
type IPList struct {
        sync.Mutex
        ips []net.IP
}

func (list *IPList) Add(ip net.IP) {
        list.Lock()
        defer list.Unlock()

        list.ips = append(list.ips, ip)
}

func (list *IPList) Rotate() net.IP {
        list.Lock()
        defer list.Unlock()

        if len(list.ips) == 0 {
                return nil
        }

        ip := list.ips[0]
        list.ips = list.ips[1:]
        list.ips = append(list.ips, ip)

        return ip
}

func main() {
        ipList := &IPList{}

        ipList.Add(net.ParseIP("192.168.1.1"))
        ipList.Add(net.ParseIP("192.168.1.2"))
        ipList.Add(net.ParseIP("192.168.1.3"))
        ipList.Add(net.ParseIP("192.168.1.4"))

**Comment by aandrew-me** [comment]
> IP-rotater just to explain i had chat GPT add this but from my understanding their is an added structure of ip's that changes pre-entered ip's before and after each use
> 
> CODE: type IPList struct { sync.Mutex ips []net.IP }
> 
> func (list *IPList) Add(ip net.IP) { list.Lock() defer list.Unlock()
> 
> ```
>     list.ips = append(list.ips, ip)
> ```
> 
> }
> 
> func (list *IPList) Rotate() net.IP { list.Lock() defer list.Unlock()
> 
> ```
>     if len(list.ips) == 0 {
>             return nil
>     }
> 
>     ip := list.ips[0]
>     list.ips = list.ips[1:]
>     list.ips = append(list.ips, ip)
> 
>     return ip
> ```
> 
> }
> 
> func main() { ipList := &IPList{}
> 
> ```
>     ipList.Add(net.ParseIP("192.168.1.1"))
>     ipList.Add(net.ParseIP("192.168.1.2"))
>     ipList.Add(net.ParseIP("192.168.1.3"))
>     ipList.Add(net.ParseIP("192.168.1.4"))
> ```

I don't see how this code solves the problem

**Comment by aandrew-me** [comment]
Guys please see if this issue is still there in 1.4.0. I made some major changes which should fix it

**Comment by hunsrus** [comment]
It's working great for me, thanks!

**Comment by aandrew-me** [comment]
> It's working great for me, thanks!
> 
> Edit: I just ran into an issue while testing it:
> 
> ```
> panic: context deadline exceeded
> 
> goroutine 1 [running]:
> main.getData({0x7ffdec2f55bd, 0x2d}, {0xc0001a21b3, 0x26}, {0xc0001fa000, 0x1a}, 0x0)
> 	/home/runner/work/tgpt/tgpt/functions.go:204 +0x1065
> main.main()
> 	/home/runner/work/tgpt/tgpt/main.go:101 +0x8ea
> ```
> 
> But i guess it should be treated as a different issue, just letting you know. It looks like the ip block error it's solved

That issue has been addressed in the latest update

**Comment by hunsrus** [comment]
I have found a way to still get this error, you may want to look into it.
To reproduce it you have to give tgpt a prompt containing the backslash character.

**Comment by aandrew-me** [comment]
> I have found a way to still get this error, you may want to look into it. To reproduce it you have to give tgpt a prompt containing the backslash character.

Ok backslash was creating a problem, I made a change and it should fix it. Expect it in 1.4.4

**Comment by xplshn** [comment]
> Guys please see if this issue is still there in 1.4.1. I made some major changes which should fix it

Its working great, I use it as a WIKILESS(Wikipedia proxy) "replacement"
